### PR TITLE
Write downloaded files atomically

### LINKED ISSUE #1: Test shakiness on concurrent test file download
For a while I have witnessed tests in DICOM-rs occasionally failing when trying to fetch the path to an arbitrary test file.
The errors which occur are diverse, spanning from bad file hash, missing files, and sometimes even incomplete files.

After a lot of tinkering, I realized that this happens when multiple tests try to fetch the same file concurrently. This can be reproduced sometimes by creating multiple tests and letting them run concurrently, or with the following test.

```rust
#[test]
fn load_a_single_path_concurrent() {
    let handles: Vec<_> = (0..8).map(|_| std::thread::spawn(load_a_single_path_1)).collect();
    for h in handles {
        h.join().unwrap();
    }
}
```

I am already looking into ways to mitigate this problem, but any feedback, questions, or pointers on this matter is welcome.

### PR DESCRIPTION
**Pull request by Enet4**
Fixes #1.

- Save downloaded contents into a temporary file first, moving it after.
- Adjust tests to cover fetching the same file multiple times simultaneously.

### CODE REVIEW

File: rust/src/lib.rs [hunk 1]
```diff
@@ -136,12 +148,10 @@ mod tests {
     use super::*;
 
     #[test]
-    fn load_a_single_path() {
+    fn load_a_single_path_1() {
```
Comment (robyoung) [inline rust/src/lib.rs:151]: Do you still need this function?

Comment (Enet4) [reply rust/src/lib.rs:151]: It's an independent test function, so I decided to keep it and introduce a separate function for the concurrent loading test.

**Review by robyoung — APPROVED** [review]
